export const FIND_CARD_REQUEST = "FIND_CARD_REQUEST"
export const FIND_CARD_SUCCESS = "FIND_CARD_SUCCESS"
export const FIND_CARD_FAILURE = "FIND_CARD_FAILURE"

export const CLEAR_CARD_REQUEST = "CLEAR_CARD_REQUEST"
export const CLEAR_CARD_SUCCESS = "CLEAR_CARD_SUCCESS"
export const CLEAR_CARD_FAILURE = "CLEAR_CARD_FAILURE"

export const GET_ALL_CARD_ITEMS_REQUEST = "GET_ALL_CARD_ITEMS_REQUEST"
export const GET_ALL_CARD_ITEMS_SUCCESS = "GET_ALL_CARD_ITEMS_SUCCESS"
export const GET_ALL_CARD_ITEMS_FAILURE = "GET_ALL_CARD_ITEMS_FAILURE"

export const ADD_ITEM_TO_CARD_REQUEST = "ADD_ITEM_TO_CARD_REQUEST"
export const ADD_ITEM_TO_CARD_SUCCESS = "ADD_ITEM_TO_CARD_SUCCESS"
export const ADD_ITEM_TO_CARD_FAILURE = "ADD_ITEM_TO_CARD_FAILURE"

export const UPDATE_CARD_ITEM_REQUEST = "UPDATE_CARD_ITEM_REQUEST"
export const UPDATE_CARD_ITEM_SUCCESS = "UPDATE_CARD_ITEM_SUCCESS"
export const UPDATE_CARD_ITEM_FAILURE = "UPDATE_CARD_ITEM_FAILURE"

export const REMOVE_CARD_ITEM_REQUEST = "REMOVE_CARD_ITEM_REQUEST"
export const REMOVE_CARD_ITEM_SUCCESS = "REMOVE_CARD_ITEM_SUCCESS"
export const REMOVE_CARD_ITEM_FAILURE = "REMOVE_CARD_ITEM_FAILURE"